version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "08:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: husky
    versions:
    - 4.3.6
    - 4.3.8
  - dependency-name: lint-staged
    versions:
    - 10.5.3
  - dependency-name: ini
    versions:
    - 1.3.7
  - dependency-name: react-scripts
    versions:
    - 4.0.1
  - dependency-name: phoenix
    versions:
    - 1.5.7
